return {
    ensure_installed = {
        "bash",
        "css",
        "go",
        "html",
        "javascript",
        "json",
        "lua",
        "luadoc",
        "python",
        "rust",
        "typescript",
        "yaml",
        "dockerfile",
        "mermaid",
        "vim",
        "vimdoc",
        "latex",
        "norg",
        "scss",
        "svelte",
        "tsx",
        "vue",
        "typst",
        "regex"
    },
}
